# Site settings
title: Michael Lee
email: hellomichaellee@gmail.com
description: "Michael Lee is a craftsman of digital and analog things."
baseurl: ""
url: "http://michaellee.co"
paginate: 4
paginate_path: "/page/:num"

exclude: ['sass/', 'CNAME', 'Gemfile', 'Gemfile.lock', 's3_website.yml']

# Build settings
markdown: redcarpet
permalink: /:title

collections:
  javascript:
    output: true
    permalink: /learning/javascript/:path/
  vim:
    output: true
    permalink: /learning/vim/:path/
  swift:
    output: true
    permalink: /learning/swift/:path/