# Site settings
title: "Michael Lee"
email: "michaelsoolee@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Michael Lee is a craftsman of digital things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelsoolee.com" # the base hostname & protocol for your site
twitter_username: michaelsoolee
github_username:  michaellee

# Build settings
markdown: redcarpet
permalink: /:title
paginate: 4
paginate_path: "/page/:num"

sass:
  style: :compressed

collections:
  notes:
    output: true
    permalink: /notes/:path/

gems: [jekyll-paginate]
