# Site settings
title: Michael Lee
email: hellomichaellee@gmail.com
description: "Michael Lee is a craftsman of digital and analog things."
baseurl: ""
url: "http://michaellee.co"
paginate: 4

exclude: ['sass/']

# Build settings
markdown: redcarpet
permalink: /:title
