# Site settings
title: "Michael Lee"
email: "hellomichaellee@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Michael Lee is a craftsman of digital and analog things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaellee.co" # the base hostname & protocol for your site
twitter_username: hellomichaellee
github_username:  michaellee

# Build settings
markdown: kramdown
permalink: /:title
paginate: 4
paginate_path: "/page/:num"

github:
  repo: michaellee/michaellee.github.io
  branch: master

exclude: ["s3_website.yml"]